name: container workflow
on: push

jobs:
  build:
    name: Hello world jobs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Taseer"
